#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleFeeds
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="azymut")]
	public partial class FeedsDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public FeedsDataContextDataContext() : 
				base(global::GoogleFeeds.Properties.Settings.Default.azymutConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FeedsDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FeedsDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FeedsDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FeedsDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ITidea_GoogleFeeds")]
		public ISingleResult<ITidea_GoogleFeedsResult> ITidea_GoogleFeeds()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ITidea_GoogleFeedsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _EAN;
		
		private string _ISBN;
		
		private string _ISSN;
		
		private string _AzymutId;
		
		private System.Nullable<long> _PlatonId;
		
		private string _dzial;
		
		private string _autorzy;
		
		private string _redakcja;
		
		private string _tytul;
		
		private string _podtytul;
		
		private string _liczbatomo;
		
		private string _nrkolejnyt;
		
		private string _tytultomu;
		
		private string _jezykoryg;
		
		private string _tytuloryg;
		
		private string _tlumacze;
		
		private string _jezyki;
		
		private string _seriacykl;
		
		private string _tematyka;
		
		private string _wydawca;
		
		private System.Nullable<int> _azymutKodWydawcy;
		
		private string _wydanie;
		
		private string _rokwyd;
		
		private string _objetosc;
		
		private string _format;
		
		private string _oprawa;
		
		private string _oprawaUproszczona;
		
		private System.Nullable<decimal> _ciezar;
		
		private string _uwagi;
		
		private string _isbn_serii;
		
		private string _opis;
		
		private string _opisSkrocony;
		
		private string _miejscowosc;
		
		private string _wysokosc;
		
		private string _typ_pub;
		
		private string _kompl1;
		
		private string _kompl2;
		
		private System.Nullable<decimal> _cenaDetBrutto;
		
		private System.Nullable<decimal> _cenaHurtNetto;
		
		private System.Nullable<bool> _AzymutPrzecena;
		
		private string _pkwiu;
		
		private System.Nullable<int> _vat;
		
		private System.Nullable<int> _dostepnosc;
		
		private System.Nullable<int> _dostepnoscTemp;
		
		private System.Nullable<int> _czasRealizacji;
		
		private System.Nullable<System.DateTime> _ostatnioDostepny;
		
		private System.Nullable<System.DateTime> _ostatnioDostepnyTemp;
		
		private System.Nullable<bool> _zapowiedz;
		
		private System.Nullable<System.DateTime> _data_ukazania_sie;
		
		private System.Nullable<int> _statusObrazka;
		
		private System.Nullable<System.DateTime> _statusObrazkaLastUpdate;
		
		private string _obrazekPlik;
		
		private System.Nullable<int> _ukryjProdukt;
		
		private System.Nullable<short> _ukryjProduktTemp;
		
		private System.Nullable<int> _InHowManyOrders;
		
		private System.Nullable<int> _InHowManyOrders30;
		
		private System.Nullable<System.DateTime> _LastUpdated;
		
		private System.Nullable<int> _OrderBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEANChanging(string value);
    partial void OnEANChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void OnISSNChanging(string value);
    partial void OnISSNChanged();
    partial void OnAzymutIdChanging(string value);
    partial void OnAzymutIdChanged();
    partial void OnPlatonIdChanging(System.Nullable<long> value);
    partial void OnPlatonIdChanged();
    partial void OndzialChanging(string value);
    partial void OndzialChanged();
    partial void OnautorzyChanging(string value);
    partial void OnautorzyChanged();
    partial void OnredakcjaChanging(string value);
    partial void OnredakcjaChanged();
    partial void OntytulChanging(string value);
    partial void OntytulChanged();
    partial void OnpodtytulChanging(string value);
    partial void OnpodtytulChanged();
    partial void OnliczbatomoChanging(string value);
    partial void OnliczbatomoChanged();
    partial void OnnrkolejnytChanging(string value);
    partial void OnnrkolejnytChanged();
    partial void OntytultomuChanging(string value);
    partial void OntytultomuChanged();
    partial void OnjezykorygChanging(string value);
    partial void OnjezykorygChanged();
    partial void OntytulorygChanging(string value);
    partial void OntytulorygChanged();
    partial void OntlumaczeChanging(string value);
    partial void OntlumaczeChanged();
    partial void OnjezykiChanging(string value);
    partial void OnjezykiChanged();
    partial void OnseriacyklChanging(string value);
    partial void OnseriacyklChanged();
    partial void OntematykaChanging(string value);
    partial void OntematykaChanged();
    partial void OnwydawcaChanging(string value);
    partial void OnwydawcaChanged();
    partial void OnazymutKodWydawcyChanging(System.Nullable<int> value);
    partial void OnazymutKodWydawcyChanged();
    partial void OnwydanieChanging(string value);
    partial void OnwydanieChanged();
    partial void OnrokwydChanging(string value);
    partial void OnrokwydChanged();
    partial void OnobjetoscChanging(string value);
    partial void OnobjetoscChanged();
    partial void OnformatChanging(string value);
    partial void OnformatChanged();
    partial void OnoprawaChanging(string value);
    partial void OnoprawaChanged();
    partial void OnoprawaUproszczonaChanging(string value);
    partial void OnoprawaUproszczonaChanged();
    partial void OnciezarChanging(System.Nullable<decimal> value);
    partial void OnciezarChanged();
    partial void OnuwagiChanging(string value);
    partial void OnuwagiChanged();
    partial void Onisbn_seriiChanging(string value);
    partial void Onisbn_seriiChanged();
    partial void OnopisChanging(string value);
    partial void OnopisChanged();
    partial void OnopisSkroconyChanging(string value);
    partial void OnopisSkroconyChanged();
    partial void OnmiejscowoscChanging(string value);
    partial void OnmiejscowoscChanged();
    partial void OnwysokoscChanging(string value);
    partial void OnwysokoscChanged();
    partial void Ontyp_pubChanging(string value);
    partial void Ontyp_pubChanged();
    partial void Onkompl1Changing(string value);
    partial void Onkompl1Changed();
    partial void Onkompl2Changing(string value);
    partial void Onkompl2Changed();
    partial void OncenaDetBruttoChanging(System.Nullable<decimal> value);
    partial void OncenaDetBruttoChanged();
    partial void OncenaHurtNettoChanging(System.Nullable<decimal> value);
    partial void OncenaHurtNettoChanged();
    partial void OnAzymutPrzecenaChanging(System.Nullable<bool> value);
    partial void OnAzymutPrzecenaChanged();
    partial void OnpkwiuChanging(string value);
    partial void OnpkwiuChanged();
    partial void OnvatChanging(System.Nullable<int> value);
    partial void OnvatChanged();
    partial void OndostepnoscChanging(System.Nullable<int> value);
    partial void OndostepnoscChanged();
    partial void OndostepnoscTempChanging(System.Nullable<int> value);
    partial void OndostepnoscTempChanged();
    partial void OnczasRealizacjiChanging(System.Nullable<int> value);
    partial void OnczasRealizacjiChanged();
    partial void OnostatnioDostepnyChanging(System.Nullable<System.DateTime> value);
    partial void OnostatnioDostepnyChanged();
    partial void OnostatnioDostepnyTempChanging(System.Nullable<System.DateTime> value);
    partial void OnostatnioDostepnyTempChanged();
    partial void OnzapowiedzChanging(System.Nullable<bool> value);
    partial void OnzapowiedzChanged();
    partial void Ondata_ukazania_sieChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_ukazania_sieChanged();
    partial void OnstatusObrazkaChanging(System.Nullable<int> value);
    partial void OnstatusObrazkaChanged();
    partial void OnstatusObrazkaLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnstatusObrazkaLastUpdateChanged();
    partial void OnobrazekPlikChanging(string value);
    partial void OnobrazekPlikChanged();
    partial void OnukryjProduktChanging(System.Nullable<int> value);
    partial void OnukryjProduktChanged();
    partial void OnukryjProduktTempChanging(System.Nullable<short> value);
    partial void OnukryjProduktTempChanged();
    partial void OnInHowManyOrdersChanging(System.Nullable<int> value);
    partial void OnInHowManyOrdersChanged();
    partial void OnInHowManyOrders30Changing(System.Nullable<int> value);
    partial void OnInHowManyOrders30Changed();
    partial void OnLastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdatedChanged();
    partial void OnOrderByChanging(System.Nullable<int> value);
    partial void OnOrderByChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EAN", DbType="NVarChar(20)")]
		public string EAN
		{
			get
			{
				return this._EAN;
			}
			set
			{
				if ((this._EAN != value))
				{
					this.OnEANChanging(value);
					this.SendPropertyChanging();
					this._EAN = value;
					this.SendPropertyChanged("EAN");
					this.OnEANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(20)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSN", DbType="NVarChar(20)")]
		public string ISSN
		{
			get
			{
				return this._ISSN;
			}
			set
			{
				if ((this._ISSN != value))
				{
					this.OnISSNChanging(value);
					this.SendPropertyChanging();
					this._ISSN = value;
					this.SendPropertyChanged("ISSN");
					this.OnISSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzymutId", DbType="Char(13)")]
		public string AzymutId
		{
			get
			{
				return this._AzymutId;
			}
			set
			{
				if ((this._AzymutId != value))
				{
					this.OnAzymutIdChanging(value);
					this.SendPropertyChanging();
					this._AzymutId = value;
					this.SendPropertyChanged("AzymutId");
					this.OnAzymutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlatonId", DbType="BigInt")]
		public System.Nullable<long> PlatonId
		{
			get
			{
				return this._PlatonId;
			}
			set
			{
				if ((this._PlatonId != value))
				{
					this.OnPlatonIdChanging(value);
					this.SendPropertyChanging();
					this._PlatonId = value;
					this.SendPropertyChanged("PlatonId");
					this.OnPlatonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dzial", DbType="VarChar(5)")]
		public string dzial
		{
			get
			{
				return this._dzial;
			}
			set
			{
				if ((this._dzial != value))
				{
					this.OndzialChanging(value);
					this.SendPropertyChanging();
					this._dzial = value;
					this.SendPropertyChanged("dzial");
					this.OndzialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autorzy", DbType="NVarChar(250)")]
		public string autorzy
		{
			get
			{
				return this._autorzy;
			}
			set
			{
				if ((this._autorzy != value))
				{
					this.OnautorzyChanging(value);
					this.SendPropertyChanging();
					this._autorzy = value;
					this.SendPropertyChanged("autorzy");
					this.OnautorzyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_redakcja", DbType="NVarChar(250)")]
		public string redakcja
		{
			get
			{
				return this._redakcja;
			}
			set
			{
				if ((this._redakcja != value))
				{
					this.OnredakcjaChanging(value);
					this.SendPropertyChanging();
					this._redakcja = value;
					this.SendPropertyChanged("redakcja");
					this.OnredakcjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tytul", DbType="NVarChar(500)")]
		public string tytul
		{
			get
			{
				return this._tytul;
			}
			set
			{
				if ((this._tytul != value))
				{
					this.OntytulChanging(value);
					this.SendPropertyChanging();
					this._tytul = value;
					this.SendPropertyChanged("tytul");
					this.OntytulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_podtytul", DbType="NVarChar(500)")]
		public string podtytul
		{
			get
			{
				return this._podtytul;
			}
			set
			{
				if ((this._podtytul != value))
				{
					this.OnpodtytulChanging(value);
					this.SendPropertyChanging();
					this._podtytul = value;
					this.SendPropertyChanged("podtytul");
					this.OnpodtytulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liczbatomo", DbType="NVarChar(50)")]
		public string liczbatomo
		{
			get
			{
				return this._liczbatomo;
			}
			set
			{
				if ((this._liczbatomo != value))
				{
					this.OnliczbatomoChanging(value);
					this.SendPropertyChanging();
					this._liczbatomo = value;
					this.SendPropertyChanged("liczbatomo");
					this.OnliczbatomoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrkolejnyt", DbType="NVarChar(50)")]
		public string nrkolejnyt
		{
			get
			{
				return this._nrkolejnyt;
			}
			set
			{
				if ((this._nrkolejnyt != value))
				{
					this.OnnrkolejnytChanging(value);
					this.SendPropertyChanging();
					this._nrkolejnyt = value;
					this.SendPropertyChanged("nrkolejnyt");
					this.OnnrkolejnytChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tytultomu", DbType="NVarChar(500)")]
		public string tytultomu
		{
			get
			{
				return this._tytultomu;
			}
			set
			{
				if ((this._tytultomu != value))
				{
					this.OntytultomuChanging(value);
					this.SendPropertyChanging();
					this._tytultomu = value;
					this.SendPropertyChanged("tytultomu");
					this.OntytultomuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jezykoryg", DbType="NVarChar(100)")]
		public string jezykoryg
		{
			get
			{
				return this._jezykoryg;
			}
			set
			{
				if ((this._jezykoryg != value))
				{
					this.OnjezykorygChanging(value);
					this.SendPropertyChanging();
					this._jezykoryg = value;
					this.SendPropertyChanged("jezykoryg");
					this.OnjezykorygChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tytuloryg", DbType="NVarChar(500)")]
		public string tytuloryg
		{
			get
			{
				return this._tytuloryg;
			}
			set
			{
				if ((this._tytuloryg != value))
				{
					this.OntytulorygChanging(value);
					this.SendPropertyChanging();
					this._tytuloryg = value;
					this.SendPropertyChanged("tytuloryg");
					this.OntytulorygChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlumacze", DbType="NVarChar(250)")]
		public string tlumacze
		{
			get
			{
				return this._tlumacze;
			}
			set
			{
				if ((this._tlumacze != value))
				{
					this.OntlumaczeChanging(value);
					this.SendPropertyChanging();
					this._tlumacze = value;
					this.SendPropertyChanged("tlumacze");
					this.OntlumaczeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jezyki", DbType="NVarChar(250)")]
		public string jezyki
		{
			get
			{
				return this._jezyki;
			}
			set
			{
				if ((this._jezyki != value))
				{
					this.OnjezykiChanging(value);
					this.SendPropertyChanging();
					this._jezyki = value;
					this.SendPropertyChanged("jezyki");
					this.OnjezykiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seriacykl", DbType="NVarChar(100)")]
		public string seriacykl
		{
			get
			{
				return this._seriacykl;
			}
			set
			{
				if ((this._seriacykl != value))
				{
					this.OnseriacyklChanging(value);
					this.SendPropertyChanging();
					this._seriacykl = value;
					this.SendPropertyChanged("seriacykl");
					this.OnseriacyklChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tematyka", DbType="NVarChar(10)")]
		public string tematyka
		{
			get
			{
				return this._tematyka;
			}
			set
			{
				if ((this._tematyka != value))
				{
					this.OntematykaChanging(value);
					this.SendPropertyChanging();
					this._tematyka = value;
					this.SendPropertyChanged("tematyka");
					this.OntematykaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wydawca", DbType="NVarChar(100)")]
		public string wydawca
		{
			get
			{
				return this._wydawca;
			}
			set
			{
				if ((this._wydawca != value))
				{
					this.OnwydawcaChanging(value);
					this.SendPropertyChanging();
					this._wydawca = value;
					this.SendPropertyChanged("wydawca");
					this.OnwydawcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_azymutKodWydawcy", DbType="Int")]
		public System.Nullable<int> azymutKodWydawcy
		{
			get
			{
				return this._azymutKodWydawcy;
			}
			set
			{
				if ((this._azymutKodWydawcy != value))
				{
					this.OnazymutKodWydawcyChanging(value);
					this.SendPropertyChanging();
					this._azymutKodWydawcy = value;
					this.SendPropertyChanged("azymutKodWydawcy");
					this.OnazymutKodWydawcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wydanie", DbType="NVarChar(50)")]
		public string wydanie
		{
			get
			{
				return this._wydanie;
			}
			set
			{
				if ((this._wydanie != value))
				{
					this.OnwydanieChanging(value);
					this.SendPropertyChanging();
					this._wydanie = value;
					this.SendPropertyChanged("wydanie");
					this.OnwydanieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rokwyd", DbType="NVarChar(10)")]
		public string rokwyd
		{
			get
			{
				return this._rokwyd;
			}
			set
			{
				if ((this._rokwyd != value))
				{
					this.OnrokwydChanging(value);
					this.SendPropertyChanging();
					this._rokwyd = value;
					this.SendPropertyChanged("rokwyd");
					this.OnrokwydChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objetosc", DbType="NVarChar(10)")]
		public string objetosc
		{
			get
			{
				return this._objetosc;
			}
			set
			{
				if ((this._objetosc != value))
				{
					this.OnobjetoscChanging(value);
					this.SendPropertyChanging();
					this._objetosc = value;
					this.SendPropertyChanged("objetosc");
					this.OnobjetoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format", DbType="NVarChar(50)")]
		public string format
		{
			get
			{
				return this._format;
			}
			set
			{
				if ((this._format != value))
				{
					this.OnformatChanging(value);
					this.SendPropertyChanging();
					this._format = value;
					this.SendPropertyChanged("format");
					this.OnformatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oprawa", DbType="NVarChar(50)")]
		public string oprawa
		{
			get
			{
				return this._oprawa;
			}
			set
			{
				if ((this._oprawa != value))
				{
					this.OnoprawaChanging(value);
					this.SendPropertyChanging();
					this._oprawa = value;
					this.SendPropertyChanged("oprawa");
					this.OnoprawaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oprawaUproszczona", DbType="NVarChar(50)")]
		public string oprawaUproszczona
		{
			get
			{
				return this._oprawaUproszczona;
			}
			set
			{
				if ((this._oprawaUproszczona != value))
				{
					this.OnoprawaUproszczonaChanging(value);
					this.SendPropertyChanging();
					this._oprawaUproszczona = value;
					this.SendPropertyChanged("oprawaUproszczona");
					this.OnoprawaUproszczonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciezar", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> ciezar
		{
			get
			{
				return this._ciezar;
			}
			set
			{
				if ((this._ciezar != value))
				{
					this.OnciezarChanging(value);
					this.SendPropertyChanging();
					this._ciezar = value;
					this.SendPropertyChanged("ciezar");
					this.OnciezarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uwagi", DbType="NVarChar(500)")]
		public string uwagi
		{
			get
			{
				return this._uwagi;
			}
			set
			{
				if ((this._uwagi != value))
				{
					this.OnuwagiChanging(value);
					this.SendPropertyChanging();
					this._uwagi = value;
					this.SendPropertyChanged("uwagi");
					this.OnuwagiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbn_serii", DbType="NVarChar(20)")]
		public string isbn_serii
		{
			get
			{
				return this._isbn_serii;
			}
			set
			{
				if ((this._isbn_serii != value))
				{
					this.Onisbn_seriiChanging(value);
					this.SendPropertyChanging();
					this._isbn_serii = value;
					this.SendPropertyChanged("isbn_serii");
					this.Onisbn_seriiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis", DbType="NVarChar(MAX)")]
		public string opis
		{
			get
			{
				return this._opis;
			}
			set
			{
				if ((this._opis != value))
				{
					this.OnopisChanging(value);
					this.SendPropertyChanging();
					this._opis = value;
					this.SendPropertyChanged("opis");
					this.OnopisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opisSkrocony", DbType="NVarChar(MAX)")]
		public string opisSkrocony
		{
			get
			{
				return this._opisSkrocony;
			}
			set
			{
				if ((this._opisSkrocony != value))
				{
					this.OnopisSkroconyChanging(value);
					this.SendPropertyChanging();
					this._opisSkrocony = value;
					this.SendPropertyChanged("opisSkrocony");
					this.OnopisSkroconyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miejscowosc", DbType="NVarChar(100)")]
		public string miejscowosc
		{
			get
			{
				return this._miejscowosc;
			}
			set
			{
				if ((this._miejscowosc != value))
				{
					this.OnmiejscowoscChanging(value);
					this.SendPropertyChanging();
					this._miejscowosc = value;
					this.SendPropertyChanged("miejscowosc");
					this.OnmiejscowoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wysokosc", DbType="NVarChar(20)")]
		public string wysokosc
		{
			get
			{
				return this._wysokosc;
			}
			set
			{
				if ((this._wysokosc != value))
				{
					this.OnwysokoscChanging(value);
					this.SendPropertyChanging();
					this._wysokosc = value;
					this.SendPropertyChanged("wysokosc");
					this.OnwysokoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ_pub", DbType="NChar(2)")]
		public string typ_pub
		{
			get
			{
				return this._typ_pub;
			}
			set
			{
				if ((this._typ_pub != value))
				{
					this.Ontyp_pubChanging(value);
					this.SendPropertyChanging();
					this._typ_pub = value;
					this.SendPropertyChanged("typ_pub");
					this.Ontyp_pubChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kompl1", DbType="Char(13)")]
		public string kompl1
		{
			get
			{
				return this._kompl1;
			}
			set
			{
				if ((this._kompl1 != value))
				{
					this.Onkompl1Changing(value);
					this.SendPropertyChanging();
					this._kompl1 = value;
					this.SendPropertyChanged("kompl1");
					this.Onkompl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kompl2", DbType="Char(13)")]
		public string kompl2
		{
			get
			{
				return this._kompl2;
			}
			set
			{
				if ((this._kompl2 != value))
				{
					this.Onkompl2Changing(value);
					this.SendPropertyChanging();
					this._kompl2 = value;
					this.SendPropertyChanged("kompl2");
					this.Onkompl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cenaDetBrutto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cenaDetBrutto
		{
			get
			{
				return this._cenaDetBrutto;
			}
			set
			{
				if ((this._cenaDetBrutto != value))
				{
					this.OncenaDetBruttoChanging(value);
					this.SendPropertyChanging();
					this._cenaDetBrutto = value;
					this.SendPropertyChanged("cenaDetBrutto");
					this.OncenaDetBruttoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cenaHurtNetto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cenaHurtNetto
		{
			get
			{
				return this._cenaHurtNetto;
			}
			set
			{
				if ((this._cenaHurtNetto != value))
				{
					this.OncenaHurtNettoChanging(value);
					this.SendPropertyChanging();
					this._cenaHurtNetto = value;
					this.SendPropertyChanged("cenaHurtNetto");
					this.OncenaHurtNettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzymutPrzecena", DbType="Bit")]
		public System.Nullable<bool> AzymutPrzecena
		{
			get
			{
				return this._AzymutPrzecena;
			}
			set
			{
				if ((this._AzymutPrzecena != value))
				{
					this.OnAzymutPrzecenaChanging(value);
					this.SendPropertyChanging();
					this._AzymutPrzecena = value;
					this.SendPropertyChanged("AzymutPrzecena");
					this.OnAzymutPrzecenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkwiu", DbType="VarChar(20)")]
		public string pkwiu
		{
			get
			{
				return this._pkwiu;
			}
			set
			{
				if ((this._pkwiu != value))
				{
					this.OnpkwiuChanging(value);
					this.SendPropertyChanging();
					this._pkwiu = value;
					this.SendPropertyChanged("pkwiu");
					this.OnpkwiuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vat", DbType="Int")]
		public System.Nullable<int> vat
		{
			get
			{
				return this._vat;
			}
			set
			{
				if ((this._vat != value))
				{
					this.OnvatChanging(value);
					this.SendPropertyChanging();
					this._vat = value;
					this.SendPropertyChanged("vat");
					this.OnvatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dostepnosc", DbType="Int")]
		public System.Nullable<int> dostepnosc
		{
			get
			{
				return this._dostepnosc;
			}
			set
			{
				if ((this._dostepnosc != value))
				{
					this.OndostepnoscChanging(value);
					this.SendPropertyChanging();
					this._dostepnosc = value;
					this.SendPropertyChanged("dostepnosc");
					this.OndostepnoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dostepnoscTemp", DbType="Int")]
		public System.Nullable<int> dostepnoscTemp
		{
			get
			{
				return this._dostepnoscTemp;
			}
			set
			{
				if ((this._dostepnoscTemp != value))
				{
					this.OndostepnoscTempChanging(value);
					this.SendPropertyChanging();
					this._dostepnoscTemp = value;
					this.SendPropertyChanged("dostepnoscTemp");
					this.OndostepnoscTempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czasRealizacji", DbType="Int")]
		public System.Nullable<int> czasRealizacji
		{
			get
			{
				return this._czasRealizacji;
			}
			set
			{
				if ((this._czasRealizacji != value))
				{
					this.OnczasRealizacjiChanging(value);
					this.SendPropertyChanging();
					this._czasRealizacji = value;
					this.SendPropertyChanged("czasRealizacji");
					this.OnczasRealizacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ostatnioDostepny", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ostatnioDostepny
		{
			get
			{
				return this._ostatnioDostepny;
			}
			set
			{
				if ((this._ostatnioDostepny != value))
				{
					this.OnostatnioDostepnyChanging(value);
					this.SendPropertyChanging();
					this._ostatnioDostepny = value;
					this.SendPropertyChanged("ostatnioDostepny");
					this.OnostatnioDostepnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ostatnioDostepnyTemp", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ostatnioDostepnyTemp
		{
			get
			{
				return this._ostatnioDostepnyTemp;
			}
			set
			{
				if ((this._ostatnioDostepnyTemp != value))
				{
					this.OnostatnioDostepnyTempChanging(value);
					this.SendPropertyChanging();
					this._ostatnioDostepnyTemp = value;
					this.SendPropertyChanged("ostatnioDostepnyTemp");
					this.OnostatnioDostepnyTempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zapowiedz", DbType="Bit")]
		public System.Nullable<bool> zapowiedz
		{
			get
			{
				return this._zapowiedz;
			}
			set
			{
				if ((this._zapowiedz != value))
				{
					this.OnzapowiedzChanging(value);
					this.SendPropertyChanging();
					this._zapowiedz = value;
					this.SendPropertyChanged("zapowiedz");
					this.OnzapowiedzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_ukazania_sie", DbType="Date")]
		public System.Nullable<System.DateTime> data_ukazania_sie
		{
			get
			{
				return this._data_ukazania_sie;
			}
			set
			{
				if ((this._data_ukazania_sie != value))
				{
					this.Ondata_ukazania_sieChanging(value);
					this.SendPropertyChanging();
					this._data_ukazania_sie = value;
					this.SendPropertyChanged("data_ukazania_sie");
					this.Ondata_ukazania_sieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusObrazka", DbType="Int")]
		public System.Nullable<int> statusObrazka
		{
			get
			{
				return this._statusObrazka;
			}
			set
			{
				if ((this._statusObrazka != value))
				{
					this.OnstatusObrazkaChanging(value);
					this.SendPropertyChanging();
					this._statusObrazka = value;
					this.SendPropertyChanged("statusObrazka");
					this.OnstatusObrazkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusObrazkaLastUpdate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> statusObrazkaLastUpdate
		{
			get
			{
				return this._statusObrazkaLastUpdate;
			}
			set
			{
				if ((this._statusObrazkaLastUpdate != value))
				{
					this.OnstatusObrazkaLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._statusObrazkaLastUpdate = value;
					this.SendPropertyChanged("statusObrazkaLastUpdate");
					this.OnstatusObrazkaLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obrazekPlik", DbType="NVarChar(50)")]
		public string obrazekPlik
		{
			get
			{
				return this._obrazekPlik;
			}
			set
			{
				if ((this._obrazekPlik != value))
				{
					this.OnobrazekPlikChanging(value);
					this.SendPropertyChanging();
					this._obrazekPlik = value;
					this.SendPropertyChanged("obrazekPlik");
					this.OnobrazekPlikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukryjProdukt", DbType="Int")]
		public System.Nullable<int> ukryjProdukt
		{
			get
			{
				return this._ukryjProdukt;
			}
			set
			{
				if ((this._ukryjProdukt != value))
				{
					this.OnukryjProduktChanging(value);
					this.SendPropertyChanging();
					this._ukryjProdukt = value;
					this.SendPropertyChanged("ukryjProdukt");
					this.OnukryjProduktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukryjProduktTemp", DbType="SmallInt")]
		public System.Nullable<short> ukryjProduktTemp
		{
			get
			{
				return this._ukryjProduktTemp;
			}
			set
			{
				if ((this._ukryjProduktTemp != value))
				{
					this.OnukryjProduktTempChanging(value);
					this.SendPropertyChanging();
					this._ukryjProduktTemp = value;
					this.SendPropertyChanged("ukryjProduktTemp");
					this.OnukryjProduktTempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InHowManyOrders", DbType="Int")]
		public System.Nullable<int> InHowManyOrders
		{
			get
			{
				return this._InHowManyOrders;
			}
			set
			{
				if ((this._InHowManyOrders != value))
				{
					this.OnInHowManyOrdersChanging(value);
					this.SendPropertyChanging();
					this._InHowManyOrders = value;
					this.SendPropertyChanged("InHowManyOrders");
					this.OnInHowManyOrdersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InHowManyOrders30", DbType="Int")]
		public System.Nullable<int> InHowManyOrders30
		{
			get
			{
				return this._InHowManyOrders30;
			}
			set
			{
				if ((this._InHowManyOrders30 != value))
				{
					this.OnInHowManyOrders30Changing(value);
					this.SendPropertyChanging();
					this._InHowManyOrders30 = value;
					this.SendPropertyChanged("InHowManyOrders30");
					this.OnInHowManyOrders30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this.OnLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._LastUpdated = value;
					this.SendPropertyChanged("LastUpdated");
					this.OnLastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderBy", DbType="Int")]
		public System.Nullable<int> OrderBy
		{
			get
			{
				return this._OrderBy;
			}
			set
			{
				if ((this._OrderBy != value))
				{
					this.OnOrderByChanging(value);
					this.SendPropertyChanging();
					this._OrderBy = value;
					this.SendPropertyChanged("OrderBy");
					this.OnOrderByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ITidea_GoogleFeedsResult
	{
		
		private int _productID;
		
		private string _title;
		
		private string _author;
		
		private string _tytuloryg;
		
		private string _tlumacze;
		
		private decimal _price;
		
		private decimal _oldprice;
		
		private string _shortdescription;
		
		private string _BookCover;
		
		private decimal _Weight;
		
		private decimal _ciezar;
		
		private string _dzial;
		
		private bool _OutOffStock;
		
		private string _isbn;
		
		private string _img_uri;
		
		private string _img_uri_src;
		
		public ITidea_GoogleFeedsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int NOT NULL")]
		public int productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					this._productID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="NVarChar(200)")]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this._author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tytuloryg", DbType="NVarChar(500)")]
		public string tytuloryg
		{
			get
			{
				return this._tytuloryg;
			}
			set
			{
				if ((this._tytuloryg != value))
				{
					this._tytuloryg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlumacze", DbType="NVarChar(250)")]
		public string tlumacze
		{
			get
			{
				return this._tlumacze;
			}
			set
			{
				if ((this._tlumacze != value))
				{
					this._tlumacze = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,4) NOT NULL")]
		public decimal price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oldprice", DbType="Decimal(18,4) NOT NULL")]
		public decimal oldprice
		{
			get
			{
				return this._oldprice;
			}
			set
			{
				if ((this._oldprice != value))
				{
					this._oldprice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortdescription", DbType="NVarChar(MAX)")]
		public string shortdescription
		{
			get
			{
				return this._shortdescription;
			}
			set
			{
				if ((this._shortdescription != value))
				{
					this._shortdescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookCover", DbType="NVarChar(100)")]
		public string BookCover
		{
			get
			{
				return this._BookCover;
			}
			set
			{
				if ((this._BookCover != value))
				{
					this._BookCover = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(18,4) NOT NULL")]
		public decimal Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciezar", DbType="Decimal(18,2) NOT NULL")]
		public decimal ciezar
		{
			get
			{
				return this._ciezar;
			}
			set
			{
				if ((this._ciezar != value))
				{
					this._ciezar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dzial", DbType="VarChar(5)")]
		public string dzial
		{
			get
			{
				return this._dzial;
			}
			set
			{
				if ((this._dzial != value))
				{
					this._dzial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutOffStock", DbType="Bit NOT NULL")]
		public bool OutOffStock
		{
			get
			{
				return this._OutOffStock;
			}
			set
			{
				if ((this._OutOffStock != value))
				{
					this._OutOffStock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbn", DbType="NVarChar(20)")]
		public string isbn
		{
			get
			{
				return this._isbn;
			}
			set
			{
				if ((this._isbn != value))
				{
					this._isbn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_uri", DbType="VarChar(39)")]
		public string img_uri
		{
			get
			{
				return this._img_uri;
			}
			set
			{
				if ((this._img_uri != value))
				{
					this._img_uri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_uri_src", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string img_uri_src
		{
			get
			{
				return this._img_uri_src;
			}
			set
			{
				if ((this._img_uri_src != value))
				{
					this._img_uri_src = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
