#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TireFu")]
	public partial class KeywordStatsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGoogleKeywordAnalytic(GoogleKeywordAnalytic instance);
    partial void UpdateGoogleKeywordAnalytic(GoogleKeywordAnalytic instance);
    partial void DeleteGoogleKeywordAnalytic(GoogleKeywordAnalytic instance);
    #endregion
		
		public KeywordStatsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TireFuConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordStatsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordStatsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordStatsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordStatsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GoogleKeywordAnalytic> GoogleKeywordAnalytics
		{
			get
			{
				return this.GetTable<GoogleKeywordAnalytic>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItIdea_SEO_MVGooglKeywordAnalytics")]
	public partial class GoogleKeywordAnalytic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pageUri;
		
		private string _googleKeyword;
		
		private int _sumcount;
		
		private float _bounceRate;
		
		private System.DateTime _lastUpdate;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpageUriChanging(string value);
    partial void OnpageUriChanged();
    partial void OngoogleKeywordChanging(string value);
    partial void OngoogleKeywordChanged();
    partial void OnsumcountChanging(int value);
    partial void OnsumcountChanged();
    partial void OnbounceRateChanging(float value);
    partial void OnbounceRateChanged();
    partial void OnlastUpdateChanging(System.DateTime value);
    partial void OnlastUpdateChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public GoogleKeywordAnalytic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageUri", DbType="NVarChar(500) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string pageUri
		{
			get
			{
				return this._pageUri;
			}
			set
			{
				if ((this._pageUri != value))
				{
					this.OnpageUriChanging(value);
					this.SendPropertyChanging();
					this._pageUri = value;
					this.SendPropertyChanged("pageUri");
					this.OnpageUriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_googleKeyword", DbType="NVarChar(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string googleKeyword
		{
			get
			{
				return this._googleKeyword;
			}
			set
			{
				if ((this._googleKeyword != value))
				{
					this.OngoogleKeywordChanging(value);
					this.SendPropertyChanging();
					this._googleKeyword = value;
					this.SendPropertyChanged("googleKeyword");
					this.OngoogleKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sumcount", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int sumcount
		{
			get
			{
				return this._sumcount;
			}
			set
			{
				if ((this._sumcount != value))
				{
					this.OnsumcountChanging(value);
					this.SendPropertyChanging();
					this._sumcount = value;
					this.SendPropertyChanged("sumcount");
					this.OnsumcountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bounceRate", DbType="Real NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public float bounceRate
		{
			get
			{
				return this._bounceRate;
			}
			set
			{
				if ((this._bounceRate != value))
				{
					this.OnbounceRateChanging(value);
					this.SendPropertyChanging();
					this._bounceRate = value;
					this.SendPropertyChanged("bounceRate");
					this.OnbounceRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastUpdate", AutoSync=AutoSync.Always, DbType="Datetime NOT NULL", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.DateTime lastUpdate
		{
			get
			{
				return this._lastUpdate;
			}
			set
			{
				if ((this._lastUpdate != value))
				{
					this.OnlastUpdateChanging(value);
					this.SendPropertyChanging();
					this._lastUpdate = value;
					this.SendPropertyChanged("lastUpdate");
					this.OnlastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.WhenChanged)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
